### ISSUE TITLE
Textcomplete doesn't work in AngularJS UI Bootstrap accordion...

### ISSUE THREAD

**Issue by bdesilva** [yuku/textcomplete#193]
Hi, I really like your textcomplete plugin as I need this for multi-autocomplete suggestions in my textarea element. However, I require this plugin to be inside my AngularJS app's Accordion field which is part of the UI Bootstrap library. For some reason, textcomplete doesn't show the matches when inside the 
 <accordion></accordion> element, however it works outside of it.
Here is a link to Bootstrap UI's accordion control: https://angular-ui.github.io/bootstrap/#/accordion

Can you please help me with this?

Thanks.

**Comment by namaljayathunga** [comment]
Yes, Me to. Also not work with ReactJS.
Thanks.
