### ISSUE TITLE
Escape should keep the menu closed when we press Backspace

### ISSUE THREAD

**Issue by mquandalle** [yuku/textcomplete#208]
Hi,

Thank you for this great plugin. v0.3.9 introduced the “Press <kbd>Escape</kbd> to close” feature. I think that it behaves in an unexpected way in the case I want to delete the beginning of my auto-completable input using the <kbd>Backspace</kbd> key because it pomps me again the auto-complete menu that I explicitly decided to close.

**Comment by mquandalle** [comment]
@yuku-t Would you accept a PR implement that?

**Comment by yuku-t** [comment]
All pull requests are welcome :)
I started implementing v2 with completely new code base. I'll try to support the feature in v2.
