### ISSUE TITLE
Problem with Backspace key and Enter key on SimpleMDE

### ISSUE THREAD

**Issue by vencoi** [yuku/textcomplete#255]
Hello @yuku-t,

Thanks for this great work! I am using jquery-textcomplete with [SimpleMDE](https://github.com/NextStepWebs/simplemde-markdown-editor). This is my [demo](http://bgclubs.eu/editor/). Everything goes ok, but is not possible to select an item using the Enter key. But the main problem for me is when clicked on Backspace key then the dropdown-menu disappears and must start over.

Do you have any clue?

Have a nice day!

**Comment by yuku-t** [comment]
It seems that SimpleMDE prevents click an event's default behavior before textcomplete handles it.

Can you activate textcomplete before SimpleMDE?

```js
// Now
new SimpleMDE(... );
$('textarea').textcomplete(...);

// Change as
$('textarea').textcomplete(...);
new SimpleMDE(... );
```

**Comment by vencoi** [comment]
No this does not solve the problem, after change places textcomplete stopped working :(

**Comment by vencoi** [comment]
I found what is causing the problem, SimpleMDE using its own functions for different keys:
```javascript
  // STANDARD KEYMAPS
  var keyMap = CodeMirror.keyMap = {};
  keyMap.basic = {
    "Left": "goCharLeft", "Right": "goCharRight", "Up": "goLineUp", "Down": "goLineDown",
    "End": "goLineEnd", "Home": "goLineStartSmart", "PageUp": "goPageUp", "PageDown": "goPageDown",
    "Delete": "delCharAfter", "Backspace": "delCharBefore", "Shift-Backspace": "delCharBefore",
    "Tab": "defaultTab", "Shift-Tab": "indentAuto",
    "Enter": "newlineAndIndent", "Insert": "toggleOverwrite",
    "Esc": "singleSelection"
  };`

Is there any solution for this problem?

**Comment by lluchs** [comment]
You can solve this problem by forwarding Enter and Backspace to jquery-textcomplete, like this:

```javascript
var simplemde = new SimpleMDE(...)
var textcomplete = $('.CodeMirror textarea').textcomplete(...).data('textComplete')
simplemde.codemirror.addKeyMap({
  Enter: (cm) => {
    if (textcomplete.dropdown.shown)
      tc.dropdown._enter(new KeyboardEvent('fake enter', {key: 'Enter', code: 0x1C}))
    else
      return cm.constructor.Pass
  },
  Backspace: (cm) => {
    tc.adapter._onKeyUp(new KeyboardEvent('fake backspace', {key: 'Backspace', code: 0x08})})
    return cm.constructor.Pass
  },
})
```

Note that CodeMirror creates a separate textarea which you must attach jquery-textcomplete to.
