### ISSUE TITLE
Suggestion list shows more than maxCount items

### ISSUE THREAD

**Issue by a-yakimov** [yuku/textcomplete#259]
Hi @yuku-t ,

Another issue related to drawing suggestion list. To reproduce this imagine that first search call runs long (within 1-5 seconds, ajax call) and while it receive data user able to type more symbols. In this case all next search queries placed into a stack and are waiting for completion the first search query. When eventually it is completed and result is shown all followed search queries executed very fast in comparison to the first call (from hash source for example) and in this case dropdown still have data from previous call and new data added to previous. In this scenario limitation by maxCount property is not working.

Thank you,
Alex

**Comment by yuku-t** [comment]
If a search invokes long ajax call, other searches are just ignored as long as the ajax running. I think you don't callback with `true` second argument in the search function.

```js
var searchFunc = function (term, callback, match) {
  callback(cache[term], true); // <- this
  $.getJSON('/search', { q: term }).done(callback);
};
```

**Comment by a-yakimov** [comment]
Hello!
You are right and still there is circumstances where behavior that I have described may happen.
Please take a look at  _search function (line 307 ver. 1.3.3):
        if (!stillSearching) {
          // The last callback in the current lock.
          free();
          self._clearAtNext = true; // Call dropdown.clear at the next time.
        }

The free() function will call next available _search function in stack and it will be executed prior the flag _clearAtNext will be set. Hence the additional data will be added to drop down list as it is not cleared.
To prevent this issue is needed a small delay before next search function will start working or set clearAtNext flag before free() call. Again this is the only case (I believe)  when data for suggestion list existed in hash source in memory and there is no delay to fetch them.

**Comment by a-yakimov** [comment]
And I disagree with closing this issue, it's not resolved yet. Please reopen it.
