### ISSUE TITLE
Leaking Event Handler

### ISSUE THREAD

**Issue by jlukic** [yuku/textcomplete#287]
There's currently a [bubbled event being watched on `document`](https://github.com/yuku-t/jquery-textcomplete/blob/master/src/dropdown.js#L22) that appears to be bound to `document` regardless of whether a `textcomplete` component is initialized. 

Attaching an event handler on every bubbled click event is fairly expensive. This most likely should be part of the components `initialize` and [`destroy`](https://github.com/yuku-t/jquery-textcomplete/blob/master/dist/jquery.textcomplete.js#L232) method, so that it doesn't continue to evaluate on every click event in your site/app. 

To make sure its attached once across components you'll most likely need to use some novel strategy, but it could be accomplished using something like unique ids, or namespaced events.

**Comment by yuku-t** [comment]
Hi @jlukic, thanks for opening the issue.

I agree that global click event handler costs a bit but I'm not sure it is worth optimized. Does it cause performance issues in your app?

**Comment by jlukic** [comment]
I'm working on a single page app with something like 50+ distinct pages. Only a few of them use the textcomplete component, however all click events on all pages fire the textcomplete event handler. 

There's no specific issue with the event handler performing poorly, however the design might cause memory issues. The event handler carries a reference to `dropdownViews` which prevents it from being properly garbage collected by the browser.
