### ISSUE TITLE
manually fire select?

### ISSUE THREAD

**Issue by unhammer** [yuku/textcomplete#289]
How can I manually fire select on the active drop-down? I'm considering using this with https://quilljs.com/ which of course defines its own handlers for tab in list-indentation contexts etc.; and I'd like to define a tab-handler that does completion iff there's a drop-down, otherwise runs through the other handlers.

**Comment by unhammer** [comment]
It seems I don't need to trigger it myself, as long as I can override the other tab-handlers:

```
  quill.keyboard.addBinding(
    {
      key: 9
    },
    function(_range, _context) {
      // Run the other handlers iff no dropdown:
      return $('.textcomplete-dropdown').filter(":visible").length === 0;
    }
  );
  // Give it priority over the other handlers:
  quill.keyboard.bindings[9].unshift(quill.keyboard.bindings[9].pop())
```

**Comment by nunesbeto** [comment]
Thanks a lot @unhammer! Worked for me.
