### ISSUE TITLE
Incorrect example code on main page

### ISSUE THREAD

**Issue by prostynick** [yuku/textcomplete#295]
The code on main page in "Synopsis" section is incorrect. There's no "index: 1" defined, so the code doesn't work.

**Comment by dperel** [comment]
I found that the line below from that example was not setting the `word` variable in the ternary statement. 
`return word.indexOf(term) === 0 ? word : null;`
It needs to be
`word = word.indexOf(term) === 0 ? word : null;`
in order for it to work properly. 

Minor issue aside this is a great library. Thanks!
