### ISSUE TITLE
Support CodeMirror 6

### ISSUE THREAD

**Issue by ohakutsu** [yuku/textcomplete#351]
CodeMirror 6 is currently in beta release.
https://codemirror.net/6/
https://github.com/codemirror/codemirror.next

The interface has changed in CodeMirror 6. Therefore, `@textcomplete/codemirror` don't work with CodeMirror 6.

**Comment by ohakutsu** [comment]
@yuku 
I plan to implement CodeMirror 6 support and send a Pull Request.
However, since CodeMirror 6 is still in beta, I'm hesitant to include it in `@textcomplete/codemirror`. So I'm considering creating  `@textcomplete/codemirror-next` package.

If you have any ideas, please let me know.

**Comment by yuku** [comment]
Hi, thanks for considering to contribute to this project.

I think you should create a new repository and publish it as your own npm package such as `textcomplete-codemirror-6`. In this way, you can completely control your code so it's much easier to develop. As you know, textcomplete/core doesn't care where an editor is defined, as long as it implements [the Editor class](https://github.com/yuku/textcomplete/blob/16c6684fb5d577f13193e4ec0625c8e71b706b12/packages/textcomplete-core/src/Editor.ts#L16) correctly.

I'm fine to add a link referencing the repository by the README.

**Comment by ohakutsu** [comment]
@yuku 
Thanks for the reply.
We'll consider publishing the npm package ourselves.

Thank you so much!
