### ISSUE TITLE
CKEditor integration issue

### ISSUE THREAD

**Issue by munchell** [yuku/textcomplete#90]
Hi,

I am writing a Drupal plugin to incorporate your textcomplete plugin. https://www.drupal.org/sandbox/adammitchell/2291661

However I am having issues with the integration. CKEditor puts it's contenteditable inside an iframe so I had to slightly alter the plugin to use this.el.ownerDocument.getSelection().getRangeAt(0); instead of window.getSelection().getRangeAt(0);. After doing this I now get issues with CKEditor as I type. I wonder if you could help?

The issue is IndexSizeError: Index or size is negative or greater than the allowed amount on line 371 of ckeditor.js

Any insight into the issue would be greatly appreciated.

**Comment by kjhangiani** [comment]
@munchell: had this issue, and forked the repo and fixed it there.  I'll submit a pull request soon, but try out these changes to fix the positioning:

https://github.com/soxhub/jquery-textcomplete/commit/89729d4a5cfc0046d5c18290c9498e2fd38799dd

I've only tested this with tinyMCE, but the logic should be the same for ckeditor

**Comment by amenk** [comment]
On which element did you call the `textcomplete()` after your fix?

**Comment by amenk** [comment]
Okay I was able to do something like this:

    jQuery('#issue_edit_textarea iframe').contents().find('body').textcomplete({})

**Comment by amenk** [comment]
@kjhangiani Thanks for your fix. Any news about your Pull Request :-) ?

**Comment by amenk** [comment]
But I have problems with it: When I press tab oder enter it is not properly completed. Any idea?

**Comment by amenk** [comment]
Looks like the enter/tab keypress is still handled by the input field - and t he preventDefault does not work

Not sure if the solution suggested in http://ckeditor.com/forums/CKEditor-3.x/Submit-Enter-key is any different

**Comment by amenk** [comment]
I think there might be an issue with the ContentEditable adapter. The getTextFromHeadToCaret does not seem to work (current Google Chrome).

Using this debug code:

https://github.com/arkhitech/redmine_mentions/commit/e7cf3ba5e93235fd1b11e11ea043f062559a0510

I type
`@sk` and press tab (the full completion would be `@skh`)

When in a normal textbox the console log looks like this:

	Text from head to caret >> 
	Text from head to caret >> @
	Text from head to caret >> @s
	Text from head to caret >> @sk
	PRE @sk
	_enter

But with the ContentEditable:

	Text from head to caret >> @
	Text from head to caret >> @s
	Text from head to caret >> @sk
	PRE @s
	_enter

Any help is appreciated!

**Comment by amenk** [comment]
it actually seems to be some weird event timing issue. When I click the matched entry, everything works fine. The key press event might be processed to later?

**Comment by amenk** [comment]
See also: http://stackoverflow.com/questions/35604045/why-is-canceling-a-key-down-not-working-if-i-display-an-alert

**Comment by amenk** [comment]
The textcomplete plugin does not seem to properly prevent the default keyup event, when pressing ENTER / TAB

**Comment by amenk** [comment]
Maybe this helps: http://stackoverflow.com/questions/13526065/preventing-ckeditor-to-display-character-on-keypress

**Comment by amenk** [comment]
I can not get it fixed ... But I was able to intercept the keypress events for ENTER with a hack like this:

    _bindEvents: function () {
      CKEDITOR.instances.issue_notes.on('key', function(e) {
         $.proxy(this._onKeyup, this)
          if (e.data.keyCode == 13 || e.data.keyCode == 8) {
              e.cancel();
            }
      }

But then the autocomplete is not executed anymore.

@yuku-t What do you think, how much effort is it to fix this for you? Are you available for hire?

**Comment by amenk** [comment]
I got a workaround! EasyRedmine uses the config option `config.tabSpaces = 4` in CKEditor - without that option, everything works fine!

**Comment by amenk** [comment]
But it would be nice to be compatible with the CKEditor `tab`. Ckeditor allows to define priorities for listeners. But no clue if those are in any way compatible with the JQuery listeners ?
