### ISSUE TITLE
Spaces inside search terms

### ISSUE THREAD

**Issue by thevasya** [yuku/textcomplete#99]
Hi.

I want to do something similar to [the example 4 from the demo page](http://yuku-t.com/jquery-textcomplete/) but with spaces inside search terms.

This is a test array: `names = ["John Smith", "Jane Smith"]`.

And this is related settings:

``` javascript
match: /\b(\w{2,}|\w{2,}( ?\w*))$/,
search: function (term, callback) {
    callback($.map(names, function (item) {
        console.log( term );
        return item.toLowerCase().indexOf(term.toLowerCase()) === 0 ? item : null;
    }));
},
index: 1,
```

This works fine for  `john` and `john smi`, but for the string `my friend john` it does not work. When another one space is entered, suggestion appears again: `my friend john smi`. 

From the `console.log` I see that it is trying to match `friend john` for the non-working case which is fine for the right part of regex (and the match pattern I use here is obviously incorrect).

My question is: can this task be done with a proper regex? Is it possible to use several patterns for matching?

Thanks!

**Comment by nazibra** [comment]
@thevasya how do i use your code with ajax ?

**Comment by thevasya** [comment]
@nazibra I believe you have to first obtain a list of terms for autocompletion (`names` in the above example) with ajax and then call `$('textarea').textcomplete([ ... ]);` again on your `textarea` element to re-initialize the plugin.
